### PR TITLE
DT-1217 + DT-1266

### PR DESCRIPTION
**Pull request by nt-gt**

### CODE REVIEW

**Comment by nt-gt** [comment]
@preetamnpr did you  have a look at this one?

**Comment by preetamnpr** [comment]
> @preetamnpr did you have a look at this one?

I will review it ASAP, probably I missed the automated review notification.

**Comment by preetamnpr** [comment]
Looks like the title of the PR and changes in the PR seems to be mismatch?

**Comment by nt-gt** [comment]
> Looks like the title of the PR and changes in the PR seems to be mismatch?

I cannot see the issue? There are two commits, one for each Jira issue listed in the title and the Jira issues in the commit titles match those of the Jira issues in the title. What do you feel the mismatch is?

**Comment by preetamnpr** [comment]
> > Looks like the title of the PR and changes in the PR seems to be mismatch?
> 
> I cannot see the issue? There are two commits, one for each Jira issue listed in the title and the Jira issues in the commit titles match those of the Jira issues in the title. What do you feel the mismatch is?

Does the PR have the changes for DT-1217 ?

**Comment by preetamnpr** [comment]
> > > Looks like the title of the PR and changes in the PR seems to be mismatch?
> > 
> > 
> > I cannot see the issue? There are two commits, one for each Jira issue listed in the title and the Jira issues in the commit titles match those of the Jira issues in the title. What do you feel the mismatch is?
> 
> Does the PR have the changes for DT-1217 ?

I was under the impression that George will provide us the explanation o handling 202 with no notification.  I am bit confused here.

**Review by preetamnpr — APPROVED** [review]

**Comment by nt-gt** [comment]
> > > > Looks like the title of the PR and changes in the PR seems to be mismatch?
> > > 
> > > 
> > > I cannot see the issue? There are two commits, one for each Jira issue listed in the title and the Jira issues in the commit titles match those of the Jira issues in the title. What do you feel the mismatch is?
> > 
> > 
> > Does the PR have the changes for DT-1217 ?
> 
> I was under the impression that George will provide us the explanation of handling 202 with no notification. Since its Ebl Surrender and I hope that applicable changes belongs to DT-1217 and DT-1266.

Ah, this change is not about the `202` change that apply for BKG and eBL. Instead it moves to 204 for a different reason (consistency with other API calls in these APIs). The `DT-1217` should have been `DT-1267`.

Apologies for the confusion.

**Pull request merged**
