### PR TITLE
SD-676 EBL-ICS2 Changes Conditional Validations

### PR DESCRIPTION
**Pull request by palatsangeetha**
### **PR Type**
enhancement, tests

___

### **Description**
- Added several new conditional validation checks in `EBLChecks.java` to ensure data integrity based on specific conditions.
- Introduced `EXEMPT_PACKAGE_CODES` in `EblDatasets.java` to support new validation logic.
- Updated JSON request example in `ebl-api-3.0.0-request.json` to include new fields and scenarios for testing.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>EBLChecks.java</strong><dd><code>Add conditional validation checks for EBL fields</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

ebl/src/main/java/org/dcsa/conformance/standards/ebl/checks/EBLChecks.java

<li>Added multiple conditional validation checks for various fields.<br> <li> Introduced new checks for manifest type and house bill of lading <br>conditions.<br> <li> Reorganized array order handling for routing of consignment countries.<br> <br>

</details>

  </td>
  <td><a href="https://github.com/dcsaorg/Conformance-Gateway/pull/237/files#diff-e45bcf9f51c94f0c72632f7a40f04a3bb184896801843c0c97cf4a4dad1ee8a8">+301/-14</a></td>

</tr>

<tr>
  <td>
    <details>
      <summary><strong>EblDatasets.java</strong><dd><code>Add exempt package codes dataset</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

ebl/src/main/java/org/dcsa/conformance/standards/ebl/checks/EblDatasets.java

- Added `EXEMPT_PACKAGE_CODES` dataset.

</details>

  </td>
  <td><a href="https://github.com/dcsaorg/Conformance-Gateway/pull/237/files#diff-cf98df85588aa7b9a52011751dbb93ad55da645327edf82e93832b773104f0fa">+1/-2</a>&nbsp; &nbsp; &nbsp; </td>

</tr>
</table></td></tr><tr><td><strong>Tests</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>ebl-api-3.0.0-request.json</strong><dd><code>Update JSON request example with new fields</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

ebl/src/main/resources/standards/ebl/messages/ebl-api-3.0.0-request.json

<li>Added new fields for advance manifest filings and house bill of <br>ladings.<br> <li> Updated example data to include new validation scenarios.<br>

</details>

  </td>
  <td><a href="https://github.com/dcsaorg/Conformance-Gateway/pull/237/files#diff-3e1f83a80cfe7f82a7dd949377b6c9f7ae42db4c8bb5c147ed696506f65fbf7e">+78/-0</a>&nbsp; &nbsp; </td>

</tr>
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**: Comment `/help "your question"` on any pull request to receive relevant information

### CODE REVIEW

**Review by jkosternl — APPROVED** [review]
Regarding the Java part: please add empty lines between the methods and format `EBLChecks.java` so it is easier to read. For the rest, I think it looks fine.
I assume Preetam checks if the checks make sense 😉 
Almost forgot the mention: but do you also add unit tests?

**Review by preetamnpr — CHANGES_REQUESTED** [review]
As discussed, use the existing available methods in JsonAttribute to validate the attributes

**Comment by palatsangeetha** [comment]
> As discussed, use the existing available methods in JsonAttribute to validate the attributes

Thanks @preetamnpr for the comments, I will change this to the existing methods. Will add unit tests too.

**Review by jkosternl — APPROVED** [review]
Nice! Got 83.2% coverage in this PR 👍🏻

**Review by preetamnpr — APPROVED** [review]
THe changes looks fine.

**Pull request merged**
